import { Typography, Drawer, List, ListItem, ListItemIcon, ListItemText, Container, Box } from '@material-ui/core';
import DashboardIcon from '@material-ui/icons/Dashboard';
import DevicesIcon from '@material-ui/icons/Devices';
import PeopleIcon from '@material-ui/icons/People';
import LabelImportantIcon from '@material-ui/icons/LabelImportant';
import AssessmentIcon from '@material-ui/icons/Assessment';
import MonetizationOnSharpIcon from '@material-ui/icons/MonetizationOnSharp';
import MenuBookTwoToneIcon from '@material-ui/icons/MenuBookTwoTone';
import AssignmentTwoToneIcon from '@material-ui/icons/AssignmentTwoTone';
import { useHistory, useLocation } from 'react-router-dom'

import useStyles from './MyStyle';



function MyDrawer() {

    const classes = useStyles();
    const history = useHistory();
    const location = useLocation();

    const menuItems = [
        {
            text: 'Dashboard',
            icon: <DashboardIcon style={{color:"#ffffff",height:"35",width:"40px" }}/>,
            path: '/'
        },
        {
            text: 'Client Details',
            icon: <PeopleIcon style={{color:"ffffff",height:"35",width:"40px"}} />,
            path: '/devices'
        },
        {
            text: 'Case Files',
            icon: <AssignmentTwoToneIcon style={{color:"#ffffff",height:"35",width:"40px"}} />,
            path: '/users'
        },
        {
            text: 'Day Book',
            icon: <MenuBookTwoToneIcon style={{color:"#ffffff",height:"35",width:"50px"}} />,
            path: '/entity'
        },
        {
            text: 'Payment',
            icon: <MonetizationOnSharpIcon style={{color:"#ffffff",height:"35",width:"40px"}} />,
            path: '/reports'
        },
        


    ]

    return (


       
        <Drawer className={classes.drawer}
            variant="permanent"
            anchor="left"
            classes={{ paper: classes.drawerPaper }}
        >

            <div  style={{backgroundColor:"black",height:"25vh"}}>
                <Typography variant="h5"  className={classes.title}>Nyayvadi</Typography>
                <Typography variant="h5"  className={classes.title}>Notes</Typography>


            </div>



            <List>
                {menuItems.map((item) => (
                    <ListItem
                    style={{display:"flex",flexDirection:"column"}}
                        button
                        key={item.text}
                        onClick={() => history.push(item.path)}
                        className={location.pathname == item.path ? classes.active : null}
                    >
                        
                        <ListItemIcon >{item.icon}</ListItemIcon>
                        <ListItemText style={{marginRight:"20px",marginTop:"5px"}} primary={item.text} />
                        
                    </ListItem>
                ))}
            </List>
            <Box >
            <Typography >Generated By Golearn IT Solutions Copyright</Typography>
            </Box>
        </Drawer>
        
    )
}

export default MyDrawer;